using PlaceApp.Groups;
using PlaceApp.Places;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Data;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Domain.Repositories;

namespace PlaceApp
{
    public class PlaceAppDataSeederContributor : IDataSeedContributor, ITransientDependency
    {
        private readonly IPlaceRepository _placeRepository;
        private readonly IRepository<PlaceType, Guid> _placeTypeRepository;
        private readonly IRepository<Group, Guid> _groupRepository;

        private readonly PlaceManager _placeManager;

        public PlaceAppDataSeederContributor(
            IPlaceRepository placeRepository,
            IRepository<PlaceType, Guid> placeTypeRepository,
            PlaceManager placeManager,
            IRepository<Group, Guid> groupRepository
            )
        {
            _placeRepository = placeRepository;
            _placeTypeRepository = placeTypeRepository;
            _placeManager = placeManager;
            _groupRepository = groupRepository;
        }

        public async Task SeedAsync(DataSeedContext context)
        {
            if (await _placeRepository.GetCountAsync() > 0)
            {
                return;
            }
            var car = await _groupRepository.InsertAsync(new Group { Name = "Xe cộ" }, autoSave: true);
            var finance = await _groupRepository.InsertAsync(new Group { Name = "Tài chính & Ngân hàng " }, autoSave: true);
            var health = await _groupRepository.InsertAsync(new Group { Name = "Y tế và sức khoẻ " }, autoSave: true);
            var public_transport = await _groupRepository.InsertAsync(new Group { Name = "Giao thông công cộng " }, autoSave: true);
            var education = await _groupRepository.InsertAsync(new Group { Name = "Giáo dục và đào tạo " }, autoSave: true);
            var lodging = await _groupRepository.InsertAsync(new Group { Name = "Dịch vụ lưu trú " }, autoSave: true);
            var food_service = await _groupRepository.InsertAsync(new Group { Name = "Dịch vụ ăn uống " }, autoSave: true);
            var religion = await _groupRepository.InsertAsync(new Group { Name = "Tôn giáo, thờ cúng, tín ngưỡng " }, autoSave: true);
            var establishment = await _groupRepository.InsertAsync(new Group { Name = "Công ty, tổ chức, văn phòng " }, autoSave: true);
            var tourist_attraction = await _groupRepository.InsertAsync(new Group { Name = "Tham quan, du lịch " }, autoSave: true);
            var sports = await _groupRepository.InsertAsync(new Group { Name = "Thể dục & thể thao " }, autoSave: true);
            var entertainment = await _groupRepository.InsertAsync(new Group { Name = "Giải trí " }, autoSave: true);
            var government = await _groupRepository.InsertAsync(new Group { Name = "Chính quyền & địa phương " }, autoSave: true);
            var beauty = await _groupRepository.InsertAsync(new Group { Name = "Làm đẹp " }, autoSave: true);
            var fashion = await _groupRepository.InsertAsync(new Group { Name = "Thời trang " }, autoSave: true);
            var electronics_store = await _groupRepository.InsertAsync(new Group { Name = "Cửa hàng bán đồ điện tử " }, autoSave: true);
            var store = await _groupRepository.InsertAsync(new Group { Name = "Mua sắm " }, autoSave: true);
            var service = await _groupRepository.InsertAsync(new Group { Name = "Dịch vụ " }, autoSave: true);



            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Xe cộ	", Type = "	car	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đại lý xe oto	", Type = "	car_dealer	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đại lý xe máy	", Type = "	motorcycle_dealer	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đại lý xe đạp	", Type = "	bicycle_store	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ sửa xe, cứu hộ oto	", Type = "	car_repair	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ rửa xe oto, xe máy	", Type = "	car_wash	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ sửa xe máy, xe đạp	", Type = "	motorcycle_repair	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cho thuê xe ô tô	", Type = "	car_rental	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cho thuê xe xe máy, xe đạp	", Type = "	motorcycle_rental	", GroupId = car.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Tài chính	", Type = "	finance	", GroupId = finance.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	ATM	", Type = "	atm	", GroupId = finance.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Ngân hàng	", Type = "	bank	", GroupId = finance.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Kho bạc	", Type = "	treasury	", GroupId = finance.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Kế toán	", Type = "	accounting	", GroupId = finance.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ cầm đồ	", Type = "	pawn_shop	", GroupId = finance.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Sức khỏe, y tế	", Type = "	health	", GroupId = health.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà thuốc, quầy thuốc	", Type = "	pharmacy	", GroupId = health.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Bệnh viện, trạm y tế	", Type = "	hospital	", GroupId = health.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Phòng khám	", Type = "	doctor	", GroupId = health.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Vật lý trị liệu	", Type = "	physiotherapist	", GroupId = health.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nha khoa	", Type = "	dentist	", GroupId = health.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Giao thông công cộng	", Type = "	public_transport	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Bến xe	", Type = "	bus_station	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Sân bay	", Type = "	airport	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Bến đò, phà	", Type = "	ferry	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Ga tàu lửa	", Type = "	train_station	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trạm xe bus	", Type = "	bus_stop	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Ga tàu điện ngầm	", Type = "	subway_station	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trạm sạc xe điện	", Type = "	charging_station	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trạm xăng	", Type = "	gas_station	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Bãi giữ xe	", Type = "	parking	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trạm trung chuyển	", Type = "	transit_station	", GroupId = public_transport.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Giáo dục và đào tạo	", Type = "	education	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trường mầm non, mẫu giáo	", Type = "	preschool	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trường tiểu học	", Type = "	primary_school	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trường trung học cơ sở (THCS)	", Type = "	secondary_school	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trường trung học phổ thông (THPT)	", Type = "	high_school	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trường đại học	", Type = "	university	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trường cao đẳng, trung cấp, trường nghề	", Type = "	college	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trung tâm đào tạo lái xe	", Type = "	driving_school	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trung tâm đào tạo	", Type = "	training_center	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trung tâm ngoại ngữ	", Type = "	language_center	", GroupId = education.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ lưu trú (hostel, home stay)	", Type = "	lodging	", GroupId = lodging.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Khách sạn	", Type = "	hotel	", GroupId = lodging.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Chung cư, căn hộ	", Type = "	apartment	", GroupId = lodging.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Resort, villa	", Type = "	resort	", GroupId = lodging.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà nghỉ	", Type = "	guest_house	", GroupId = lodging.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ ăn uống	", Type = "	food_service	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cà phê	", Type = "	cafe	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trà sữa	", Type = "	milk_tea	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Tiệm bánh	", Type = "	bakery	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Quán ăn	", Type = "	eatery	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đồ ăn nhanh	", Type = "	fast_food	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Quán nhậu	", Type = "	beer_bar	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Quán chè	", Type = "	sweet_soup	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Giải khát, quán nước, sinh tố	", Type = "	drink	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Quán kem	", Type = "	ice_cream_shop	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đồ ăn mang đi	", Type = "	take_away	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà hàng	", Type = "	restaurant	", GroupId = food_service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Tôn giáo, tín ngưỡng	", Type = "	religion	", GroupId = religion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Chùa	", Type = "	pagoda	", GroupId = religion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đền thờ, miếu	", Type = "	temple	", GroupId = religion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nơi thờ cúng, trang nghiêm	", Type = "	worship	", GroupId = religion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà thờ thiên chúa/tin lành	", Type = "	church	", GroupId = religion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Công ty, tổ chức, hiệp hội	", Type = "	establishment	", GroupId = establishment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà kho/ kho hàng hóa	", Type = "	storage	", GroupId = establishment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Công ty xây dựng	", Type = "	construction_company	", GroupId = establishment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Kinh doanh bảo hiểm	", Type = "	insurance_agency	", GroupId = establishment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Kinh doanh bất động sản	", Type = "	real_estate_agency	", GroupId = establishment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Khu công nghiệp	", Type = "	industrial_zone	", GroupId = establishment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Công ty du lịch & lữ hành	", Type = "	travel_agency	", GroupId = establishment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Văn phòng cho thuê	", Type = "	coworking_space	", GroupId = establishment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Điểm du lịch	", Type = "	tourist_attraction	", GroupId = tourist_attraction.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Khu vực cắm trại	", Type = "	campground	", GroupId = tourist_attraction.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Bảo tàng	", Type = "	museum	", GroupId = tourist_attraction.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Bãi biển	", Type = "	public_beach	", GroupId = tourist_attraction.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Khu triển lãm	", Type = "	art_gallery	", GroupId = tourist_attraction.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Liên quan đến thể dục thể thao	", Type = "	sports	", GroupId = sports.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Phòng tập thể dục, thể hình	", Type = "	gym	", GroupId = sports.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trung tâm thể dục thể thao, nhà thi đấu	", Type = "	sports_center	", GroupId = sports.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Sân vận động	", Type = "	stadium	", GroupId = sports.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Công viên/khu vực đi bộ thư giãn	", Type = "	park	", GroupId = sports.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Sân golf	", Type = "	golf	", GroupId = sports.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Liên quan đến vui chơi, giải trí	", Type = "	entertainment	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Khu vui chơi	", Type = "	amusement_park	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Rạp chiếu phim	", Type = "	cinema	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Thư viện	", Type = "	library	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Sở thú	", Type = "	zoo	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà hát	", Type = "	theater	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ Spa/massage	", Type = "	spa	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Sòng bài	", Type = "	casino	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Hộp đêm/Vũ trường/Quán bar	", Type = "	bar	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Pub/Lougne	", Type = "	pub	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Quán karaoke	", Type = "	karaoke	", GroupId = entertainment.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Liên quan đến chính quyền, địa phương	", Type = "	government	", GroupId = government.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Tòa án	", Type = "	courthouse	", GroupId = government.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đồn/Cục cảnh sát	", Type = "	police	", GroupId = government.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	UBND, Trung tâm hành chính	", Type = "	committee	", GroupId = government.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đại sứ quán/Lãnh sứ quán/Ngoại giao	", Type = "	political	", GroupId = government.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà văn hoá, sinh hoạt cộng đồng	", Type = "	community_center	", GroupId = government.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Quảng trường	", Type = "	town_square	", GroupId = government.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trạm cứu hỏa	", Type = "	fire_station	", GroupId = government.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Liên quan đến làm đẹp	", Type = "	beauty	", GroupId = beauty.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng mỹ phẩm	", Type = "	cosmetic_store	", GroupId = beauty.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Hiệu làm tóc/nails	", Type = "	hair_care	", GroupId = beauty.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Thẩm mỹ viện, làm đẹp	", Type = "	beauty_salon	", GroupId = beauty.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Liên quan đến thời trang	", Type = "	fashion	", GroupId = fashion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng mẹ và bé	", Type = "	mommy_store	", GroupId = fashion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ may mặc	", Type = "	tailor	", GroupId = fashion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng áo quần	", Type = "	clothing_store	", GroupId = fashion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng mắt kính	", Type = "	glasses_store	", GroupId = fashion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng giày/dép	", Type = "	shoe_store	", GroupId = fashion.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng đồ điện tử	", Type = "	electronics_store	", GroupId = electronics_store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng điện thoại di động	", Type = "	cellphone_store	", GroupId = electronics_store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng máy tính	", Type = "	computer_store	", GroupId = electronics_store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng thực phẩm	", Type = "	food_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng tiện lợi 24/7", Type = "convenience_store", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Chợ	", Type = "	local_market	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Siêu thị	", Type = "	supermarket	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng tạp hóa	", Type = "	grocery_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng	", Type = "	store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng trái cây, rau quả	", Type = "	fruit_shop	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng hoa/cây cảnh	", Type = "	florist	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng đồ chơi	", Type = "	toy_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng nội thất	", Type = "	furniture_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng dụng cụ thể thao	", Type = "	sports_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng đồ gia dụng	", Type = "	home_goods_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng trang sức	", Type = "	jewelry_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà sách	", Type = "	book_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trung tâm mua sắm	", Type = "	shopping_mall	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng thú cưng	", Type = "	pet_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng bia/rượu	", Type = "	liquor_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng lưu niệm/đặc sản/quà cáp	", Type = "	gift_shop	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng vật liệu xây dựng, nội thất	", Type = "	building_materials_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng nhạc cụ	", Type = "	musical_instrument_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng điện nước	", Type = "	electrical_supply_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng nhiên liệu (gas/than/dầu/..)	", Type = "	fuel_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cửa hàng đồ cũ	", Type = "	second_hand_store	", GroupId = store.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ liên quan đến cưới hỏi	", Type = "	wedding_service	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ chuyển phát, bưu điện	", Type = "	post_office	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ giặt ủi	", Type = "	laundry	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ vận chuyển	", Type = "	moving_service	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ chụp ảnh	", Type = "	photography	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ mạng viễn thông	", Type = "	tel_service	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Đại lý du lịch/vé máy bay	", Type = "	travel_agent	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ pháp lý/công chứng	", Type = "	legal_service	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Luật sư	", Type = "	lawyer	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ in ấn, photocopy	", Type = "	photocopy	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ thú y	", Type = "	veterinary_care	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ mai táng	", Type = "	funeral_service	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ môi giới việc làm	", Type = "	employment_agency	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ vệ sinh	", Type = "	sanitation_service	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ tổ chức sự kiện	", Type = "	event_agency	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Dịch vụ sửa khóa	", Type = "	locksmith	", GroupId = service.Id }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà tù	", Type = "	prison	" }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nhà vệ sinh công cộng	", Type = "	public_restroom	" }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Nghĩa trang	", Type = "	cemetery	"}, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Thuộc về thiên nhiên	", Type = "	natural_feature	"}, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cầu	", Type = "	bridge	"}, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trạm thu phí	", Type = "	toll_booth	"}, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Cảng biển	", Type = "	harbour	" }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Liên quan đến xổ số	", Type = "	lottery	" }, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Trạm năng lương (thủy/nhiệt/gió/..)	", Type = "	power_station	"}, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Liên quan đến nông nghiệp	", Type = "	farming	"}, autoSave: true);
            await _placeTypeRepository.InsertAsync(new PlaceType { TypeName = "	Địa điểm nói chung	", Type = "	point	" }, autoSave: true);


            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Xe cộ	", "auto", StatusType.Approval, "	car	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đại lý xe oto	", "auto", StatusType.Approval, "	car_dealer	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đại lý xe máy	", "auto", StatusType.Approval, "	motorcycle_dealer	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đại lý xe đạp	", "auto", StatusType.Approval, "	bicycle_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ sửa xe, cứu hộ oto	", "auto", StatusType.Approval, "	car_repair	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ rửa xe oto, xe máy	", "auto", StatusType.Approval, "	car_wash	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ sửa xe máy, xe đạp	", "auto", StatusType.Approval, "	motorcycle_repair	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cho thuê xe ô tô	", "auto", StatusType.Approval, "	car_rental	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cho thuê xe xe máy, xe đạp	", "auto", StatusType.Approval, "	motorcycle_rental	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Tài chính	", "auto", StatusType.Approval, "	finance	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("ATM	", "auto", StatusType.Approval, "	atm	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Ngân hàng	", "auto", StatusType.Approval, "	bank	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Kho bạc	", "auto", StatusType.Approval, "	treasury	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Kế toán	", "auto", StatusType.Approval, "	accounting	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ cầm đồ	", "auto", StatusType.Approval, "	pawn_shop	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Sức khỏe, y tế	", "auto", StatusType.Approval, "	health	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà thuốc, quầy thuốc	", "auto", StatusType.Approval, "	pharmacy	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Bệnh viện, trạm y tế	", "auto", StatusType.Approval, "	hospital	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Phòng khám	", "auto", StatusType.Approval, "	doctor	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Vật lý trị liệu	", "auto", StatusType.Approval, "	physiotherapist	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nha khoa	", "auto", StatusType.Approval, "	dentist	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Giao thông công cộng	", "auto", StatusType.Approval, "	public_transport	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Bến xe	", "auto", StatusType.Approval, "	bus_station	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Sân bay	", "auto", StatusType.Approval, "	airport	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Bến đò, phà	", "auto", StatusType.Approval, "	ferry	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Ga tàu lửa	", "auto", StatusType.Approval, "	train_station	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trạm xe bus	", "auto", StatusType.Approval, "	bus_stop	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Ga tàu điện ngầm	", "auto", StatusType.Approval, "	subway_station	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trạm sạc xe điện	", "auto", StatusType.Approval, "	charging_station	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trạm xăng	", "auto", StatusType.Approval, "	gas_station	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Bãi giữ xe	", "auto", StatusType.Approval, "	parking	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trạm trung chuyển	", "auto", StatusType.Approval, "	transit_station	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Giáo dục và đào tạo	", "auto", StatusType.Approval, "	education	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trường mầm non, mẫu giáo	", "auto", StatusType.Approval, "	preschool	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trường tiểu học	", "auto", StatusType.Approval, "	primary_school	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trường trung học cơ sở (THCS)	", "auto", StatusType.Approval, "	secondary_school	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trường trung học phổ thông (THPT)	", "auto", StatusType.Approval, "	high_school	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trường đại học	", "auto", StatusType.Approval, "	university	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trường cao đẳng, trung cấp, trường nghề	", "auto", StatusType.Approval, "	college	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trung tâm đào tạo lái xe	", "auto", StatusType.Approval, "	driving_school	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trung tâm đào tạo	", "auto", StatusType.Approval, "	training_center	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trung tâm ngoại ngữ	", "auto", StatusType.Approval, "	language_center	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ lưu trú (hostel, home stay)	", "auto", StatusType.Approval, "	lodging	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Khách sạn	", "auto", StatusType.Approval, "	hotel	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Chung cư, căn hộ	", "auto", StatusType.Approval, "	apartment	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Resort, villa	", "auto", StatusType.Approval, "	resort	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà nghỉ	", "auto", StatusType.Approval, "	guest_house	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ ăn uống	", "auto", StatusType.Approval, "	food_service	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cà phê	", "auto", StatusType.Approval, "	cafe	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trà sữa	", "auto", StatusType.Approval, "	milk_tea	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Tiệm bánh	", "auto", StatusType.Approval, "	bakery	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Quán ăn	", "auto", StatusType.Approval, "	eatery	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đồ ăn nhanh	", "auto", StatusType.Approval, "	fast_food	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Quán nhậu	", "auto", StatusType.Approval, "	beer_bar	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Quán chè	", "auto", StatusType.Approval, "	sweet_soup	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Giải khát, quán nước, sinh tố	", "auto", StatusType.Approval, "	drink	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Quán kem	", "auto", StatusType.Approval, "	ice_cream_shop	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đồ ăn mang đi	", "auto", StatusType.Approval, "	take_away	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà hàng	", "auto", StatusType.Approval, "	restaurant	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Tôn giáo, tín ngưỡng	", "auto", StatusType.Approval, "	religion	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Chùa	", "auto", StatusType.Approval, "	pagoda	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đền thờ, miếu	", "auto", StatusType.Approval, "	temple	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nơi thờ cúng, trang nghiêm	", "auto", StatusType.Approval, "	worship	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà thờ thiên chúa/tin lành	", "auto", StatusType.Approval, "	church	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Công ty, tổ chức, hiệp hội	", "auto", StatusType.Approval, "	establishment	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà kho/ kho hàng hóa	", "auto", StatusType.Approval, "	storage	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Công ty xây dựng	", "auto", StatusType.Approval, "	construction_company	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Kinh doanh bảo hiểm	", "auto", StatusType.Approval, "	insurance_agency	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Kinh doanh bất động sản	", "auto", StatusType.Approval, "	real_estate_agency	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Khu công nghiệp	", "auto", StatusType.Approval, "	industrial_zone	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Công ty du lịch & lữ hành	", "auto", StatusType.Approval, "	travel_agency	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Văn phòng cho thuê	", "auto", StatusType.Approval, "	coworking_space	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Điểm du lịch	", "auto", StatusType.Approval, "	tourist_attraction	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Khu vực cắm trại	", "auto", StatusType.Approval, "	campground	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Bảo tàng	", "auto", StatusType.Approval, "	museum	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Bãi biển	", "auto", StatusType.Approval, "	public_beach	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Khu triển lãm	", "auto", StatusType.Approval, "	art_gallery	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Liên quan đến thể dục thể thao	", "auto", StatusType.Approval, "	sports	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Phòng tập thể dục, thể hình	", "auto", StatusType.Approval, "	gym	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trung tâm thể dục thể thao, nhà thi đấu	", "auto", StatusType.Approval, "	sports_center	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Sân vận động	", "auto", StatusType.Approval, "	stadium	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Công viên/khu vực đi bộ thư giãn	", "auto", StatusType.Approval, "	park	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Sân golf	", "auto", StatusType.Approval, "	golf	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Liên quan đến vui chơi, giải trí	", "auto", StatusType.Approval, "	entertainment	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Khu vui chơi	", "auto", StatusType.Approval, "	amusement_park	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Rạp chiếu phim	", "auto", StatusType.Approval, "	cinema	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Thư viện	", "auto", StatusType.Approval, "	library	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Sở thú	", "auto", StatusType.Approval, "	zoo	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà hát	", "auto", StatusType.Approval, "	theater	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ Spa/massage	", "auto", StatusType.Approval, "	spa	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Sòng bài	", "auto", StatusType.Approval, "	casino	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Hộp đêm/Vũ trường/Quán bar	", "auto", StatusType.Approval, "	bar	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Pub/Lougne	", "auto", StatusType.Approval, "	pub	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Quán karaoke	", "auto", StatusType.Approval, "	karaoke	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Liên quan đến chính quyền, địa phương	", "auto", StatusType.Approval, "	government	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Tòa án	", "auto", StatusType.Approval, "	courthouse	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đồn/Cục cảnh sát	", "auto", StatusType.Approval, "	police	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("UBND, Trung tâm hành chính	", "auto", StatusType.Approval, "	committee	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đại sứ quán/Lãnh sứ quán/Ngoại giao	", "auto", StatusType.Approval, "	political	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà văn hoá, sinh hoạt cộng đồng	", "auto", StatusType.Approval, "	community_center	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Quảng trường	", "auto", StatusType.Approval, "	town_square	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trạm cứu hỏa	", "auto", StatusType.Approval, "	fire_station	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Liên quan đến làm đẹp	", "auto", StatusType.Approval, "	beauty	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng mỹ phẩm	", "auto", StatusType.Approval, "	cosmetic_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Hiệu làm tóc/nails	", "auto", StatusType.Approval, "	hair_care	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Thẩm mỹ viện, làm đẹp	", "auto", StatusType.Approval, "	beauty_salon	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Liên quan đến thời trang	", "auto", StatusType.Approval, "	fashion	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng mẹ và bé	", "auto", StatusType.Approval, "	mommy_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ may mặc	", "auto", StatusType.Approval, "	tailor	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng áo quần	", "auto", StatusType.Approval, "	clothing_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng mắt kính	", "auto", StatusType.Approval, "	glasses_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng giày/dép	", "auto", StatusType.Approval, "	shoe_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng đồ điện tử	", "auto", StatusType.Approval, "	electronics_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng điện thoại di động	", "auto", StatusType.Approval, "	cellphone_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng máy tính	", "auto", StatusType.Approval, "	computer_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng thực phẩm	", "auto", StatusType.Approval, "	food_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng tiện lợi 24/7	", "auto", StatusType.Approval, "	convenience_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Chợ	", "auto", StatusType.Approval, "	local_market	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Siêu thị	", "auto", StatusType.Approval, "	supermarket	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng tạp hóa", "auto", StatusType.Approval, "	grocery_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng	", "auto", StatusType.Approval, "	store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng trái cây, rau quả	", "auto", StatusType.Approval, "	fruit_shop	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng hoa/cây cảnh	", "auto", StatusType.Approval, "	florist	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng đồ chơi	", "auto", StatusType.Approval, "	toy_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng nội thất	", "auto", StatusType.Approval, "	furniture_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng dụng cụ thể thao	", "auto", StatusType.Approval, "	sports_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng đồ gia dụng	", "auto", StatusType.Approval, "	home_goods_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng trang sức	", "auto", StatusType.Approval, "	jewelry_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà sách	", "auto", StatusType.Approval, "	book_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trung tâm mua sắm	", "auto", StatusType.Approval, "	shopping_mall	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng thú cưng	", "auto", StatusType.Approval, "	pet_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng bia/rượu	", "auto", StatusType.Approval, "	liquor_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng lưu niệm/đặc sản/quà cáp	", "auto", StatusType.Approval, "	gift_shop	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng vật liệu xây dựng, nội thất	", "auto", StatusType.Approval, "	building_materials_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng nhạc cụ	", "auto", StatusType.Approval, "	musical_instrument_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng điện nước	", "auto", StatusType.Approval, "	electrical_supply_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng nhiên liệu (gas/than/dầu/..)	", "auto", StatusType.Approval, "	fuel_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cửa hàng đồ cũ	", "auto", StatusType.Approval, "	second_hand_store	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ liên quan đến cưới hỏi	", "auto", StatusType.Approval, "	wedding_service	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ chuyển phát, bưu điện	", "auto", StatusType.Approval, "	post_office	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ giặt ủi	", "auto", StatusType.Approval, "	laundry	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ vận chuyển	", "auto", StatusType.Approval, "	moving_service	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ chụp ảnh	", "auto", StatusType.Approval, "	photography	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ mạng viễn thông	", "auto", StatusType.Approval, "	tel_service	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Đại lý du lịch/vé máy bay	", "auto", StatusType.Approval, "	travel_agent	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ pháp lý/công chứng	", "auto", StatusType.Approval, "	legal_service	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Luật sư	", "auto", StatusType.Approval, "	lawyer	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ in ấn, photocopy	", "auto", StatusType.Approval, "	photocopy	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ thú y	", "auto", StatusType.Approval, "	veterinary_care	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ mai táng	", "auto", StatusType.Approval, "	funeral_service	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ môi giới việc làm	", "auto", StatusType.Approval, "	employment_agency	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ vệ sinh	", "auto", StatusType.Approval, "	sanitation_service	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ tổ chức sự kiện	", "auto", StatusType.Approval, "	event_agency	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Dịch vụ sửa khóa	", "auto", StatusType.Approval, "	locksmith	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà tù	", "auto", StatusType.Approval, "	prison	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nhà vệ sinh công cộng	", "auto", StatusType.Approval, "	public_restroom	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Nghĩa trang	", "auto", StatusType.Approval, "	cemetery	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Thuộc về thiên nhiên	", "auto", StatusType.Approval, "	natural_feature	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cầu	", "auto", StatusType.Approval, "	bridge	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trạm thu phí	", "auto", StatusType.Approval, "	toll_booth	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Cảng biển	", "auto", StatusType.Approval, "	harbour	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Liên quan đến xổ số	", "auto", StatusType.Approval, "	lottery	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Trạm năng lương (thủy/nhiệt/gió/..)	", "auto", StatusType.Approval, "	power_station	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Liên quan đến nông nghiệp	", "auto", StatusType.Approval, "	farming	"));
            await _placeRepository.InsertAsync(await _placeManager.CreateAsync("Địa điểm nói chung	", "auto", StatusType.Approval, "	point	"));

        }
    }
}
